let name = "  Raghad Huzayen  ";
console.log(name.trim());
let name2 = "  Raghad  ";
console.log(name2.trimStart());
console.log(name2.trimEnd());
console.log(name2.padStart(10, "s"));
console.log(name2.padEnd(10, "e"));
console.log(name2.charAt(2));
console.log(name2.charCodeAt(2));
console.log(name.split(" "));
console.log(name2.length);
console.log(name2.slice(2, 5));
console.log(name2.substring(2, 5));
console.log(name2.substr(0, 3));
console.log(name.replace("a", "z"));
console.log(name.replaceAll("a", "z"));
console.log(name2.toUpperCase());
console.log(name2.toLowerCase());
let first = "Hello";
let second = "World";
let result = first.concat(" ", second);
console.log(result);
console.log(first.indexOf("o"));
console.log(first.lastIndexOf("l"));
console.log(second.search("r"));
console.log(name.match("Huzayen"));
let text = "cat, dog, cat";
let result_2 = text.matchAll("cat");
console.log(result_2);
console.log(text.includes("dog"));
console.log(text.startsWith("dog"));
console.log(text.endsWith("cat"));
